# -*- coding: utf-8 -*-
"""NF1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbBMWDH64iPcEO4okk710SO-0BphS9k-

# **Ingeniería de Clasificación de Riesgo en Neurofibromatosis Tipo 1 (NF1) basada en Características Clínicas: mediante Ensemble Learning**
---
* Jessica Melani Romero Lora
"""

# Importación de librerías base para comenzar con el tratamiento de limpieza y exploración de datos (EDA)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Lectura de la base de datos a partir del RAW de GitHub
url_github = 'https://raw.githubusercontent.com/frontendbby/Fun-datasets/refs/heads/main/neurofibromatosis.csv'

# Transformación a dataframe a partir de la lectura del archivo de GitHub mediante un link
df = pd.read_csv(url_github)

# Exploración del dataset y status de las variables
df.info()

# Visualización de las columnas del dataset
df.head(10)

"""# **Fase 1: Preprocesamiento y limpieza**
---
"""

# Importación de las librerías
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

# Ajuste Rápido de Nombres de Columnas: Eliminar espacios y caracteres especiales
df.columns = df.columns.str.replace(r'[^A-Za-z0-9_]+', '', regex=True) # Esta instrucción elimina (),/ etc.
df.columns = df.columns.str.replace(r'\s+', '', regex=True)             # Con esta función eliminamos posibles espacios entre caractéres o palabras

# Renombrar variables clave para asegurar uniformidad
df.rename(columns={'TumourCase': 'Tumour_Case',
                   'CafeauLaitCLS': 'Cafe_au_Lait'},
          inplace=True)

"""**División estratificada:**
---
"""

# 1. Separar X e y
# y = Tumour_Case (nuestra variable objetivo: Complicación Tumoral Severa)
y = df['Tumour_Case']

# X = Todas las demás, EXCEPTO 'Tumour_Case' y 'CaseType'!
X = df.drop(['Tumour_Case', 'CaseType'], axis=1)
print(f"Features iniciales listas para la Fase de Feature Engineering: {X.shape[1]} columnas.")

# 2. División Estratificada (80% Entrenamiento, 20% Prueba)
# Stratify=y es VITAL para el desbalance de clases y la estabilidad.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    stratify=y, random_state=42)
print("Datos divididos y listos para el entrenamiento.")

# Importación de librerías para seleccionar variables altamente correlacionadas:
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Generar la Matriz de Correlación (en el set de entrenamiento)
corr_matrix = X_train.corr().abs()

# 2. Identificar pares de variables altamente correlacionadas (umbral |0.9|)
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop_highly_correlated = [column for column in upper.columns if any(upper[column] > 0.9)]

print("--- Análisis de Correlación ---")
print(f"Features con alta correlación (>|0.9|) y que deben eliminarse: {to_drop_highly_correlated}")

# Visualización para el reporte
plt.figure(figsize=(8, 10))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm')
plt.title('Matriz de Correlación Absoluta')
plt.show()

"""# **Fase 2: Feature Engineering**
---

**Método 1: Regularización L1 (Lasso)**
#
"""

# 1. Definir el modelo con penalización L1 y GridSearchCV para encontrar el mejor C
lasso_model = LogisticRegression(penalty='l1', solver='liblinear',
                                 random_state=42, class_weight='balanced', max_iter=1000)

# Rango de C (C bajo = Alta Regularización = Más coeficientes a cero)
param_grid_lasso = {'C': np.logspace(-3, 2, 6)} # [0.001, 0.01, 0.1, 1, 10, 100]

grid_search_lasso = GridSearchCV(lasso_model, param_grid_lasso, cv=5,
                                 scoring='f1', verbose=0)
grid_search_lasso.fit(X_train, y_train)

# Extraer coeficientes no nulos del mejor modelo
best_lasso = grid_search_lasso.best_estimator_
lasso_coef = pd.Series(best_lasso.coef_[0], index=X_train.columns)

# Seleccionar features con coeficiente ABSOLUTO > 0.001
selected_lasso_features = lasso_coef[abs(lasso_coef) > 1e-3].index.tolist()

print("\n--- Resultados LASSO (L1 Regularización) ---")
print(f"Features seleccionadas por LASSO ({len(selected_lasso_features)}): {selected_lasso_features}")

"""**Método 2: Importancia de Características por Árboles (Random Forest)**



"""

# 1. Entrenar un modelo RF base (solo para la importancia)
rf_selector = RandomForestClassifier(n_estimators=100, random_state=42,
                                     class_weight='balanced', max_depth=10)
rf_selector.fit(X_train, y_train)

# 2. Extraer la importancia y ordenar
rf_importance = pd.Series(rf_selector.feature_importances_, index=X_train.columns).sort_values(ascending=False)

# 3. Definir un umbral (ej. seleccionar todas las features cuya importancia sea mayor a la media)
mean_importance = rf_importance.mean()
selected_rf_features = rf_importance[rf_importance > mean_importance].index.tolist()

print("\n--- Resultados Random Forest (Importancia de Features) ---")
print(f"Features seleccionadas por RF ({len(selected_rf_features)}): {selected_rf_features}")

"""**Subconjunto final y preparación pre- etapa 3**
---
"""

# Tomamos la Intersección con las features relevantes de ambos métodos (los resultados de cada uno)
set_lasso = set(selected_lasso_features)
set_rf = set(selected_rf_features)

# Actualizamos los sets de datos con el subconjunto final de features
FINAL_FEATURES = list(set_lasso.intersection(set_rf))

# Imprimir los resultados finales para iniciar el entrenamiento
print(f"Features Finales para el Entrenamiento ({len(FINAL_FEATURES)}):")
print(FINAL_FEATURES)

"""# **Fase 3: Modelado y validación**
---

**1. Preparación para la Validación Cruzada Estratificada**
"""

# Importación de librerías
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, f1_score, recall_score, precision_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
# Importación de modelos:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

# Define la Validación Cruzada Estratificada (K=5)
N_SPLITS = 5
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

# Inicialización del DataFrame vacío que recolectará TODOS los resultados (15 filas)
results_df = pd.DataFrame(columns=['Model', 'Fold', 'AUC', 'F1_Score', 'Recall'])

# 1. Definición Global de K-Fold y el DataFrame de Resultados
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, f1_score, recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.base import clone # Necesario para reentrenar modelos por fold

# Define la Validación Cruzada Estratificada (K=5)
N_SPLITS = 5
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

# Inicialización del DataFrame vacío que recolectará TODOS los resultados (15 filas)
results_df = pd.DataFrame(columns=['Model', 'Fold', 'AUC', 'F1_Score', 'Recall'])

# Bucle 1. RL -> RF -> XGBoost
for name, pipeline, param_grid in models:
    print(f"\n⋆ 𐙚 ̊.Ejecutando Grid Search y Evaluación para {name}⋆ 𐙚 ̊.")

    # A. GridSearchCV: Encuentra el mejor hiperparámetro para el modelo actual
    grid_search = GridSearchCV(pipeline, param_grid, cv=skf,
                               scoring='roc_auc', verbose=0, n_jobs=-1)

    # El GridSearch se entrena sobre el set de entrenamiento completo (X_train_final)
    grid_search.fit(X_train_final, y_train)

    # Obtener el mejor modelo encontrado por el GridSearch
    best_model_untuned = grid_search.best_estimator_
    print(f"Mejores parámetros para {name}: {grid_search.best_params_}")

    # B. Inicialización Local: Lista para almacenar los 5 folds de ESTE modelo
    fold_results_list = []

    # Bucle 2. ⋆ 𐙚 ̊.⋆ 𐙚 ̊.⋆ 𐙚 ̊.(Evalúa al 'best_model' encontrado)⋆ 𐙚 ̊.⋆ 𐙚 ̊.⋆ 𐙚 ̊.
    for fold_n, (train_index, test_index) in enumerate(skf.split(X_train_final, y_train)):

        # 1. División de los datos del fold
        X_train_fold, X_val_fold = X_train_final.iloc[train_index], X_train_final.iloc[test_index]
        y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[test_index]

        # 2. Ajustar el modelo clonado (fresh model) en el fold actual
        model_for_fold = clone(best_model_untuned)
        model_for_fold.fit(X_train_fold, y_train_fold)

        # 3. Predicciones y Métricas
        y_pred_proba = model_for_fold.predict_proba(X_val_fold)[:, 1]
        y_pred = model_for_fold.predict(X_val_fold)
        auc = roc_auc_score(y_val_fold, y_pred_proba)
        f1 = f1_score(y_val_fold, y_pred, zero_division=0)
        recall = recall_score(y_val_fold, y_pred, zero_division=0)

        # 4. Almacenar el resultado del fold en la lista local
        fold_results_list.append({
            'Model': name,  # Guarda el nombre correcto (RL, RF, o XGB)
            'Fold': fold_n + 1,
            'AUC': auc,
            'F1_Score': f1,
            'Recall': recall
        })

    # C. Concatenación Acumulativa: Añade los 5 resultados al results_df global
    results_df = pd.concat([results_df, pd.DataFrame(fold_results_list)], ignore_index=True)

from sklearn.base import clone

# Usaremos selected_rf_features para más diversidad de características valiosas:
X_final = X_train[selected_rf_features].copy() # Usamos features seleccionadas por Random Forest (RF)
y_final = y_train.copy()

# Inicializamos una lista vacía para recolectar todos los resultados de los folds de todos los modelos:
all_fold_results = []

for name, pipeline, param_grid in models:
    print(f"\n--- Ejecutando Grid Search y Evaluación para {name} ---")

    # Crear un objeto GridSearchCV para el modelo actual:
    grid_search = GridSearchCV(pipeline, param_grid, cv=skf,
                               scoring='roc_auc', verbose=0, n_jobs=-1)

    # Ajustar el GridSearchCV en el conjunto de entrenamiento completo (X_final, y_final):
    grid_search.fit(X_final, y_final)

    # Imprimir los mejores parámetros encontrados hasta el momento:
    print(f"Mejores parámetros para {name}: {grid_search.best_params_}")

    # Obtener el mejor estimador del Grid Search:
    best_model_unfitted = clone(grid_search.best_estimator_)

    # Iterar a través de los splits de StratifiedKFold para la evaluación detallada
    for fold_n, (train_index, test_index) in enumerate(skf.split(X_final, y_final)):

        # Dividir los datos para el fold actual
        X_train_fold, X_val_fold = X_final.iloc[train_index], X_final.iloc[test_index]
        y_train_fold, y_val_fold = y_final.iloc[train_index], y_final.iloc[test_index]

        # Ajustar el modelo (una copia limpia del mejor modelo) al conjunto de entrenamiento del fold actual
        model_for_fold = clone(best_model_unfitted)
        model_for_fold.fit(X_train_fold, y_train_fold)

        # Realizar predicciones (probabilidades y etiquetas de clase) en los datos de validación
        y_pred_proba = model_for_fold.predict_proba(X_val_fold)[:, 1]
        y_pred = model_for_fold.predict(X_val_fold)

        # Calcular métricas
        auc = roc_auc_score(y_val_fold, y_pred_proba)
        f1 = f1_score(y_val_fold, y_pred, zero_division=0)
        recall = recall_score(y_val_fold, y_pred, zero_division=0)

        # Añadir los resultados a la lista general
        all_fold_results.append({
            'Model': name,
            'Fold': fold_n + 1,
            'AUC': auc,
            'F1_Score': f1,
            'Recall': recall
        })

# Crear el DataFrame final de resultados a partir de todos los resultados recolectados
results_df = pd.DataFrame(all_fold_results)

# Calcular el promedio y la desviación estándar de las métricas por modelo
final_summary = results_df.groupby('Model')[['AUC', 'F1_Score', 'Recall']].agg(['mean', 'std']).reset_index()

# Renombrar columnas para claridad
final_summary.columns = ['Model', 'AUC_Mean', 'AUC_Std', 'F1_Mean', 'F1_Std', 'Recall_Mean', 'Recall_Std']

"""#**Fase 4: Métricas**
---


"""

# Visualización final de los resultados obtenidos:
#Tabla 1. Comparativa de la estabilidad final de los modelos
print("\n𓆝 𓆟 𓆞 𓆝 𓆟𓆝 𓆟 𓆞 𓆝 𓆟 Tabla comparativa de estabilidad final 𓆝 𓆟 𓆞 𓆝 𓆟")
print(final_summary.round(4))
print("⊹ ࣪ ﹏𓊝﹏𓂁﹏⊹ ࣪ ˖⊹ ࣪ ﹏𓊝﹏𓂁﹏⊹ ࣪ ˖⊹ ࣪ ﹏𓊝﹏𓂁﹏⊹ ࣪ ˖⊹ ࣪ ﹏𓊝﹏𓂁﹏⊹ ࣪ ˖⊹ ࣪ ﹏𓊝﹏𓂁﹏⊹ ࣪ ˖⊹ ࣪ ﹏𓊝﹏𓂁﹏⊹ ࣪ ˖")

# Visualización final de los resultados obtenidos por fold y por modelo:
# Tabla 2. Resultados detallados por fold
print("\n°❀⋆.ೃ࿔*:･Resultados detallados por Fold:°❀⋆.ೃ࿔*:")
display(results_df)

# 2. Generación de la Tabla Comparativa Final
print("\n✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩ Resultados detallados por fold ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩")
print(results_df)

final_summary = results_df.groupby('Model')[['AUC', 'F1_Score', 'Recall']].agg(['mean', 'std']).reset_index()
final_summary.columns = ['Model', 'AUC_Mean', 'AUC_Std', 'F1_Mean', 'F1_Std', 'Recall_Mean', 'Recall_Std']

# Visualizaación comparativa de la estabilidad por modelo (Recall, F1 y AUC)
# Tabla 3.
print("\n\n✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆✮ ⋆ ˚｡𖦹 ⋆｡°✩ ˚｡𖦹 ⋆｡°✩")
print("Tabla comparativa de métricas de estabilidad por modelo (RF, RL, XG Boost)")
print(final_summary.round(4))
print("✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩✮ ⋆ ˚｡𖦹 ⋆｡°✩")